<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #1f2937; font-size: 10px; }
        .header { display: table; width: 100%; margin-bottom: 6px; }
        .logo-box { display: table-cell; width: 90px; vertical-align: middle; }
        .logo-img { height: 50px; }
        .company-info { display: table-cell; vertical-align: middle; padding-left: 10px; }
        .company-name { font-size: 18px; font-weight: bold; color: #111827; }
        .company-address { font-size: 10px; color: #374151; }
        .section-title { text-align: center; font-size: 13px; font-weight: bold; margin: 16px 0 8px; text-decoration: underline; }
        .info-grid { display: table; width: 100%; margin-bottom: 14px; }
        .info-cell { display: table-cell; width: 33%; padding: 4px 0; font-size: 10px; }
        .info-label { color: #6b7280; font-size: 8px; text-transform: uppercase; }
        .info-value { font-weight: bold; color: #111827; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th { background: #eef2ff; color: #111827; text-align: left; padding: 5px 4px; font-size: 8px; border: 1px solid #9ca3af; text-transform: uppercase; }
        td { padding: 5px 4px; border: 1px solid #9ca3af; font-size: 9px; }
        .status-badge { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 8px; font-weight: bold; background: #dbeafe; color: #1e40af; }
        .footer { margin-top: 20px; font-size: 8px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo-box"><img src="{{ $logoBase64 }}" class="logo-img" alt="Makuruma Logistics"></div>
        <div class="company-info">
            <div class="company-name">MAKURUMA LOGISTICS LIMITED</div>
            <div class="company-address">P.O.Box 31902 Dar es salaam-Tanzania, Tel:+255 710 001100, +255 713 013132.</div>
        </div>
    </div>

    <div class="section-title">TRACKING REPORT</div>

    <div class="info-grid">
        <div class="info-cell">
            <div class="info-label">Truck</div>
            <div class="info-value">{{ $truck->reg_no }}</div>
        </div>
        <div class="info-cell">
            <div class="info-label">Trailer / Driver</div>
            <div class="info-value">{{ $truck->trailer->reg_no ?? '—' }} / {{ $truck->driver->full_name ?? '—' }}</div>
        </div>
        <div class="info-cell">
            <div class="info-label">Truck Status</div>
<div class="info-value">{{ ucfirst($truck->status) }}</div>
        </div>
    </div>

    @php $recentBooking = $truck->bookingTrucks->first(); @endphp
    <div class="info-grid">
        <div class="info-cell">
            <div class="info-label">Last Booking</div>
            <div class="info-value">{{ $recentBooking->tripLeg->trip->trip_number ?? '—' }}</div>
        </div>
        <div class="info-cell">
            <div class="info-label">Loading Point</div>
            <div class="info-value">{{ $recentBooking->loading_point ?? '—' }}</div>
        </div>
        <div class="info-cell">
            <div class="info-label">Offloading Point</div>
            <div class="info-value">{{ $recentBooking->offloading_point ?? '—' }}</div>
        </div>
    </div>

    <div class="info-grid">
        <div class="info-cell">
            <div class="info-label">Current Status</div>
            <div class="info-value"><span class="status-badge">{{ strtoupper(str_replace('_', ' ', $truck->current_status)) }}</span></div>
        </div>
        <div class="info-cell">
            <div class="info-label">Current Location</div>
            <div class="info-value">{{ $truck->current_location ?? '—' }}</div>
        </div>
        <div class="info-cell"></div>
    </div>

    <div class="section-title">CHECKPOINT MILESTONES</div>
    <table>
        <thead>
            <tr>
                <th>Checkpoint</th>
                <th>Arrival</th>
                <th>Dispatch</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($milestones as $m)
                <tr>
                    <td>{{ $m->checkpoint->name }}</td>
                    <td>{{ $m->arrival_at ? $m->arrival_at->format('d.m.Y H:i') : '—' }}</td>
                    <td>{{ $m->dispatch_at ? $m->dispatch_at->format('d.m.Y H:i') : '—' }}</td>
                </tr>
            @empty
                <tr><td colspan="3" style="text-align:center; color:#9ca3af;">No checkpoint data recorded yet.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by Makuruma Logistics Management System · {{ now()->format('d M Y, H:i') }}</div>
</body>
</html>