<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #1f2937;
            font-size: 10px;
        }

        .header {
            display: table;
            width: 100%;
            margin-bottom: 4px;
        }

        .logo-box {
            display: table-cell;
            width: 90px;
            vertical-align: middle;
        }

        .logo-img {
            height: 50px;
        }

        .company-info {
            display: table-cell;
            vertical-align: middle;
            padding-left: 10px;
        }

        .company-name {
            font-size: 20px;
            font-weight: bold;
            color: #111827;
        }

        .company-address {
            font-size: 11px;
            color: #374151;
        }

        .company-email {
            font-size: 12px;
            font-weight: bold;
            text-align: center;
            margin: 8px 0 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #eef2ff;
            color: #111827;
            text-align: left;
            padding: 5px 4px;
            font-size: 8px;
            border: 1px solid #9ca3af;
            text-transform: uppercase;
        }

        td {
            padding: 5px 4px;
            border: 1px solid #9ca3af;
            font-size: 9px;
        }

        .total-row td {
            font-weight: bold;
            text-align: right;
            border: none;
            padding-top: 8px;
        }

        .footer {
            margin-top: 20px;
            font-size: 8px;
            color: #9ca3af;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="logo-box"><img src="{{ $logoBase64 }}" class="logo-img" alt="Makuruma Logistics"></div>
        <div class="company-info">
            <div class="company-name">MAKURUMA LOGISTICS LIMITED</div>
            <div class="company-address">P.O.Box 31902 Dar es salaam-Tanzania, Tel:+255 710 001100, +255 713 013132.
            </div>
        </div>
    </div>
    <div class="company-email">Email: info@makurumalogisticsltd.co.tz</div>

    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>Transporter</th>
                <th>Truck</th>
                <th>Trailer</th>
                <th>Ton</th>
                <th>Drives Name</th>
                <th>Driving Lisence</th>
                <th>Passport.</th>
                <th>ETA</th>
                <th>Location</th>
                <th>Contact</th>
            </tr>
        </thead>
        <tbody>
            @php $totalTon = 0; @endphp
            @foreach ($booking->bookingTrucks as $index => $bt)
                @php
                    $license = $bt->driver?->documents->firstWhere('document_type', 'license');
                    $passport = $bt->driver?->documents->firstWhere('document_type', 'passport');
                    $totalTon += (float) ($bt->capacity ?? 0);
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>MAKURUMA LOGISTICS LTD</td>
                    <td>{{ $bt->truck->reg_no }}</td>
                    <td>{{ $bt->trailer->reg_no ?? '—' }}</td>
                    <td>{{ $bt->capacity ?? '—' }}</td>
                    <td>{{ $bt->driver->full_name ?? '—' }}</td>
                    <td>{{ $license->number ?? '—' }}</td>
                    <td>{{ $passport->number ?? '—' }}</td>
                    <td>{{ $booking->eta ? \Carbon\Carbon::parse($booking->eta)->format('d.m.Y') : '—' }}</td>
                    <td>{{ $bt->truck->current_location ?? '—' }}</td>
                    <td>{{ $bt->driver->phone ?? '—' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <table style="border: none;">
        <tr class="total-row">
            <td colspan="11" style="border: none;">{{ number_format($totalTon, 0) }}</td>
        </tr>
    </table>

    <div class="footer">Generated by Makuruma Logistics Management System · {{ now()->format('d M Y, H:i') }}</div>
</body>

</html>