<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #1f2937; font-size: 10px; }
        .header { display: table; width: 100%; margin-bottom: 6px; }
        .logo-box { display: table-cell; width: 70px; vertical-align: middle; }
        .logo-badge { background: #1e3a8a; color: #fff; font-weight: bold; font-size: 9px; padding: 6px 8px; border-radius: 4px; text-align: center; line-height: 1.3; }
        .logo-badge span { color: #f97316; }
        .company-info { display: table-cell; vertical-align: middle; padding-left: 10px; }
        .company-name { font-size: 18px; font-weight: bold; color: #111827; }
        .company-address { font-size: 10px; color: #374151; }
        .section-title { text-align: center; font-size: 13px; font-weight: bold; margin: 16px 0 8px; text-decoration: underline; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th { background: #eef2ff; color: #111827; text-align: left; padding: 5px 4px; font-size: 8px; border: 1px solid #9ca3af; text-transform: uppercase; }
        td { padding: 5px 4px; border: 1px solid #9ca3af; font-size: 9px; }
        .leg-meta { font-size: 9px; color: #4b5563; margin-bottom: 4px; }
        .footer { margin-top: 20px; font-size: 8px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo-box"><div class="logo-badge">MAKURUMA<br><span>LOGISTICS</span> LTD</div></div>
        <div class="company-info">
            <div class="company-name">MAKURUMA LOGISTICS LIMITED</div>
            <div class="company-address">P.O.Box 31902 Dar es salaam-Tanzania, Tel:+255 710 001100, +255 713 013132.</div>
        </div>
    </div>

    <div style="text-align:center; font-size:13px; font-weight:bold;">Booking {{ $trip->trip_number }}</div>

    @foreach ($trip->legs as $leg)
        <div class="section-title">{{ strtoupper($leg->direction) }} TRIP SUMMARY</div>
        <div class="leg-meta">
            <strong>Client:</strong> {{ $leg->client->company_name ?? '—' }}
            &nbsp;&nbsp; <strong>Rate:</strong> {{ $leg->rate ?? '—' }} $/mt
            &nbsp;&nbsp; <strong>ETA:</strong> {{ $leg->eta ?? '—' }}
        </div>
        <table>
            <thead>
                <tr>
                    <th>No.</th><th>Truck</th><th>Trailer</th><th>Drivers Name</th>
                    <th>Loading Point</th><th>Cargo</th><th>Loading Arrival</th>
                    <th>Offloading Point</th><th>Offloading Date</th>
                    <th>Transit Weight</th><th>Detention Charge</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($leg->bookingTrucks as $index => $bt)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $bt->truck->reg_no }}</td>
                        <td>{{ $bt->trailer->reg_no ?? '—' }}</td>
                        <td>{{ $bt->driver->full_name ?? '—' }}</td>
                        <td>{{ $bt->loading_point ?? '—' }}</td>
                        <td>{{ $bt->cargo ?? '—' }}</td>
                        <td>{{ $bt->loading_point_arrival_date ? \Carbon\Carbon::parse($bt->loading_point_arrival_date)->format('d.m.Y') : '—' }}</td>
                        <td>{{ $bt->offloading_point ?? '—' }}</td>
                        <td>{{ $bt->offloading_date ? \Carbon\Carbon::parse($bt->offloading_date)->format('d.m.Y') : '—' }}</td>
                        <td>{{ $bt->invoiced_transit_weight ?? '' }}</td>
                        <td>{{ $bt->invoiced_detention_charge ?? '' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endforeach

    <div class="footer">Generated by Makuruma Logistics Management System · {{ now()->format('d M Y, H:i') }}</div>
</body>
</html>