<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #1f2937; font-size: 10px; }
        .header { display: table; width: 100%; margin-bottom: 6px; }
        .logo-box { display: table-cell; width: 90px; vertical-align: middle; }
        .logo-img { height: 50px; }
        .company-info { display: table-cell; vertical-align: middle; padding-left: 10px; }
        .company-name { font-size: 18px; font-weight: bold; color: #111827; }
        .company-address { font-size: 10px; color: #374151; }
        .section-title { text-align: center; font-size: 16px; font-weight: bold; margin: 16px 0 8px; letter-spacing: 2px; }
        .info-grid { display: table; width: 100%; margin-bottom: 14px; }
        .info-cell { display: table-cell; width: 33%; padding: 4px 0; font-size: 10px; }
        .info-label { color: #6b7280; font-size: 8px; text-transform: uppercase; }
        .info-value { font-weight: bold; color: #111827; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th { background: #1e3a8a; color: #fff; text-align: left; padding: 6px 4px; font-size: 8px; text-transform: uppercase; }
        td { padding: 6px 4px; border-bottom: 1px solid #e5e7eb; font-size: 9px; }
        .total-row td { font-weight: bold; background: #f9fafb; border-top: 2px solid #1e3a8a; }
        .footer { margin-top: 24px; font-size: 8px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo-box"><img src="{{ $logoBase64 }}" class="logo-img" alt="Makuruma Logistics"></div>
        <div class="company-info">
            <div class="company-name">MAKURUMA LOGISTICS LIMITED</div>
            <div class="company-address">P.O.Box 31902 Dar es salaam-Tanzania, Tel:+255 710 001100, +255 713 013132.</div>
        </div>
    </div>

    <div class="section-title">INVOICE</div>

    <div class="info-grid">
        <div class="info-cell">
            <div class="info-label">Invoice Number</div>
            <div class="info-value">{{ $invoice->invoice_number }}</div>
        </div>
        <div class="info-cell">
            <div class="info-label">Date</div>
            <div class="info-value">{{ \Carbon\Carbon::parse($invoice->invoice_date)->format('d M Y') }}</div>
        </div>
        <div class="info-cell">
            <div class="info-label">Mode of Payment</div>
            <div class="info-value">{{ $invoice->mode_of_payment ?? '—' }}</div>
        </div>
    </div>

    <div class="info-grid">
        <div class="info-cell">
            <div class="info-label">Billed To</div>
            <div class="info-value">{{ $invoice->client->company_name }}</div>
        </div>
        <div class="info-cell">
            <div class="info-label">Email</div>
            <div class="info-value">{{ $invoice->client->email ?? '—' }}</div>
        </div>
        <div class="info-cell">
            <div class="info-label">Phone</div>
            <div class="info-value">{{ $invoice->client->phone ?? '—' }}</div>
        </div>
    </div>

    <table>
    <thead>
        <tr>
            <th>S/N</th>
            <th>Trip Number</th>
            <th>Truck</th>
            <th>Description</th>
            <th style="text-align:right;">Qty (t)</th>
            <th style="text-align:right;">Rate ($)</th>
            <th style="text-align:right;">Amount ($)</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($invoice->lines as $index => $line)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $line->bookingTruck->tripLeg->trip->trip_number ?? '—' }}</td>
                <td>{{ $line->bookingTruck->truck->reg_no ?? '—' }}</td>
                <td>{{ $line->description }}</td>
                <td style="text-align:right;">{{ $line->quantity ?? '—' }}</td>
                <td style="text-align:right;">{{ $line->rate ?? '—' }}</td>
                <td style="text-align:right;">{{ number_format($line->amount, 2) }}</td>
            </tr>
        @endforeach
        <tr class="total-row">
            <td colspan="6">Total</td>
            <td style="text-align:right;">{{ number_format($invoice->total_amount, 2) }}</td>
        </tr>
    </tbody>
</table>

    <div class="footer">Generated by Makuruma Logistics Management System · {{ now()->format('d M Y, H:i') }}</div>
</body>
</html>